package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CorpusMetaData generated by hbm2java
 */
public class CorpusMetaData implements java.io.Serializable {

  private long id;
  private String corpusName;
  private String description;
  private Set corpusRelations = new HashSet(0);

  public CorpusMetaData() {
  }

  public CorpusMetaData(long id) {
    this.id = id;
  }

  public CorpusMetaData(long id, String corpusName, String description, Set corpusRelations) {
    this.id = id;
    this.corpusName = corpusName;
    this.description = description;
    this.corpusRelations = corpusRelations;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getCorpusName() {
    return this.corpusName;
  }

  public void setCorpusName(String corpusName) {
    this.corpusName = corpusName;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set getCorpusRelations() {
    return this.corpusRelations;
  }

  public void setCorpusRelations(Set corpusRelations) {
    this.corpusRelations = corpusRelations;
  }

}
