package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DegreeOfMembership generated by hbm2java
 */
public class DegreeOfMembership implements java.io.Serializable {

  private long id;
  private String label;
  private BigDecimal upperBound;
  private BigDecimal lowerBound;
  private Set sentimentsForPositiveDomFk = new HashSet(0);
  private Set sentimentsForHolderCertaintyDomFk = new HashSet(0);
  private Set sentimentsForNegativeDomFk = new HashSet(0);

  public DegreeOfMembership() {
  }

  public DegreeOfMembership(long id, String label, BigDecimal upperBound, BigDecimal lowerBound) {
    this.id = id;
    this.label = label;
    this.upperBound = upperBound;
    this.lowerBound = lowerBound;
  }

  public DegreeOfMembership(long id, String label, BigDecimal upperBound, BigDecimal lowerBound,
                            Set sentimentsForPositiveDomFk, Set sentimentsForHolderCertaintyDomFk,
                            Set sentimentsForNegativeDomFk) {
    this.id = id;
    this.label = label;
    this.upperBound = upperBound;
    this.lowerBound = lowerBound;
    this.sentimentsForPositiveDomFk = sentimentsForPositiveDomFk;
    this.sentimentsForHolderCertaintyDomFk = sentimentsForHolderCertaintyDomFk;
    this.sentimentsForNegativeDomFk = sentimentsForNegativeDomFk;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public BigDecimal getUpperBound() {
    return this.upperBound;
  }

  public void setUpperBound(BigDecimal upperBound) {
    this.upperBound = upperBound;
  }

  public BigDecimal getLowerBound() {
    return this.lowerBound;
  }

  public void setLowerBound(BigDecimal lowerBound) {
    this.lowerBound = lowerBound;
  }

  public Set getSentimentsForPositiveDomFk() {
    return this.sentimentsForPositiveDomFk;
  }

  public void setSentimentsForPositiveDomFk(Set sentimentsForPositiveDomFk) {
    this.sentimentsForPositiveDomFk = sentimentsForPositiveDomFk;
  }

  public Set getSentimentsForHolderCertaintyDomFk() {
    return this.sentimentsForHolderCertaintyDomFk;
  }

  public void setSentimentsForHolderCertaintyDomFk(Set sentimentsForHolderCertaintyDomFk) {
    this.sentimentsForHolderCertaintyDomFk = sentimentsForHolderCertaintyDomFk;
  }

  public Set getSentimentsForNegativeDomFk() {
    return this.sentimentsForNegativeDomFk;
  }

  public void setSentimentsForNegativeDomFk(Set sentimentsForNegativeDomFk) {
    this.sentimentsForNegativeDomFk = sentimentsForNegativeDomFk;
  }

}
