package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType implements java.io.Serializable {

  private long id;
  private String type;
  private String description;
  private Set documentVersions = new HashSet(0);

  public DocumentType() {
  }

  public DocumentType(long id) {
    this.id = id;
  }

  public DocumentType(long id, String type, String description, Set documentVersions) {
    this.id = id;
    this.type = type;
    this.description = description;
    this.documentVersions = documentVersions;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set getDocumentVersions() {
    return this.documentVersions;
  }

  public void setDocumentVersions(Set documentVersions) {
    this.documentVersions = documentVersions;
  }

}
