package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DocumentVersion generated by hbm2java
 */
public class DocumentVersion implements java.io.Serializable {

  private long id;
  private DocumentMetaData documentMetaData;
  private Url url;
  private Url urlByOntologyUrlFk;
  private DocumentType documentType;
  private String documentName;
  private Date creationDate;
  private String description;

  public DocumentVersion() {
  }

  public DocumentVersion(long id, Url url) {
    this.id = id;
    this.url = url;
  }

  public DocumentVersion(long id, DocumentMetaData documentMetaData, Url url, Url urlByOntologyUrlFk,
                         DocumentType documentType, String documentName, Date creationDate,
                         String description) {
    this.id = id;
    this.documentMetaData = documentMetaData;
    this.url = url;
    this.urlByOntologyUrlFk = urlByOntologyUrlFk;
    this.documentType = documentType;
    this.documentName = documentName;
    this.creationDate = creationDate;
    this.description = description;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public DocumentMetaData getDocumentMetaData() {
    return this.documentMetaData;
  }

  public void setDocumentMetaData(DocumentMetaData documentMetaData) {
    this.documentMetaData = documentMetaData;
  }

  public Url getUrl() {
    return this.url;
  }

  public void setUrl(Url url) {
    this.url = url;
  }

  public Url getUrlByOntologyUrlFk() {
    return this.urlByOntologyUrlFk;
  }

  public void setUrlByOntologyUrlFk(Url urlByOntologyUrlFk) {
    this.urlByOntologyUrlFk = urlByOntologyUrlFk;
  }

  public DocumentType getDocumentType() {
    return this.documentType;
  }

  public void setDocumentType(DocumentType documentType) {
    this.documentType = documentType;
  }

  public String getDocumentName() {
    return this.documentName;
  }

  public void setDocumentName(String documentName) {
    this.documentName = documentName;
  }

  public Date getCreationDate() {
    return this.creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

}
