package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentMetaData generated by hbm2java
 */
public class DocumentMetaData implements java.io.Serializable {

  private long id;
  private Website website;
  private QueryParameter queryParameter;
  private String jsiWp3Id;
  private String url;
  private String title;
  private Long numberOfParagraphs;
  private Date publicationDate;
  private String author;
  private Date retrievalDate;
  private Integer numberOfWords;
  
  private Set documentVersions = new HashSet(0);
  private Set sentiments = new HashSet(0);
  private Set corpusRelations = new HashSet(0);

  public DocumentMetaData() {
  }

  public DocumentMetaData(long id, String jsiWp3Id) {
    this.id = id;
    this.jsiWp3Id = jsiWp3Id;
  }

  public DocumentMetaData(long id, Website website, QueryParameter queryParameter, String jsiWp3Id,
                          String url, String title, Long numberOfParagraphs, Date publicationDate,
                          String author, Date retrievalDate, Set documentVersions,Integer numberOfWords ,Set sentiments,
                          Set corpusRelations) {
    this.id = id;
    this.website = website;
    this.queryParameter = queryParameter;
    this.jsiWp3Id = jsiWp3Id;
    this.url = url;
    this.title = title;
    this.numberOfParagraphs = numberOfParagraphs;
    this.publicationDate = publicationDate;
    this.author = author;
    this.retrievalDate = retrievalDate;
    this.documentVersions = documentVersions;
    this.sentiments = sentiments;
    this.corpusRelations = corpusRelations;
    this.numberOfWords = numberOfWords;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Website getWebsite() {
    return this.website;
  }

  public void setWebsite(Website website) {
    this.website = website;
  }

  public QueryParameter getQueryParameter() {
    return this.queryParameter;
  }

  public void setQueryParameter(QueryParameter queryParameter) {
    this.queryParameter = queryParameter;
  }

  public String getJsiWp3Id() {
    return this.jsiWp3Id;
  }

  public void setJsiWp3Id(String jsiWp3Id) {
    this.jsiWp3Id = jsiWp3Id;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Long getNumberOfParagraphs() {
    return this.numberOfParagraphs;
  }

  public void setNumberOfParagraphs(Long numberOfParagraphs) {
    this.numberOfParagraphs = numberOfParagraphs;
  }

  public Date getPublicationDate() {
    return this.publicationDate;
  }

  public void setPublicationDate(Date publicationDate) {
    this.publicationDate = publicationDate;
  }

  public String getAuthor() {
    return this.author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public Date getRetrievalDate() {
    return this.retrievalDate;
  }

  public void setRetrievalDate(Date retrievalDate) {
    this.retrievalDate = retrievalDate;
  }

  public Set getDocumentVersions() {
    return this.documentVersions;
  }

  public void setDocumentVersions(Set documentVersions) {
    this.documentVersions = documentVersions;
  }

  public Set getSentiments() {
    return this.sentiments;
  }

  public void setSentiments(Set sentiments) {
    this.sentiments = sentiments;
  }

  public Set getCorpusRelations() {
    return this.corpusRelations;
  }

  public void setCorpusRelations(Set corpusRelations) {
    this.corpusRelations = corpusRelations;
  }

  public Integer getNumberOfWords() {
    return numberOfWords;
  }

  public void setNumberOfWords(Integer numberOfWords) {
    this.numberOfWords = numberOfWords;
  }

}
