package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * IndicatorType generated by hbm2java
 */
public class IndicatorType implements java.io.Serializable {

  private long id;
  private String name;
  private Set sentimentIndicators = new HashSet(0);

  public IndicatorType() {
  }

  public IndicatorType(long id) {
    this.id = id;
  }

  public IndicatorType(long id, String name, Set sentimentIndicators) {
    this.id = id;
    this.name = name;
    this.sentimentIndicators = sentimentIndicators;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getSentimentIndicators() {
    return this.sentimentIndicators;
  }

  public void setSentimentIndicators(Set sentimentIndicators) {
    this.sentimentIndicators = sentimentIndicators;
  }

}
