package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Indicator generated by hbm2java
 */
public class Indicator implements java.io.Serializable {

  private long id;
  private String ontologyConceptUri;
  private String indicatorName;
  private Set sentimentIndicators = new HashSet(0);

  public Indicator() {
  }

  public Indicator(long id) {
    this.id = id;
  }

  public Indicator(long id, String ontologyConceptUri, String indicatorName, Set sentimentIndicators) {
    this.id = id;
    this.ontologyConceptUri = ontologyConceptUri;
    this.indicatorName = indicatorName;
    this.sentimentIndicators = sentimentIndicators;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getOntologyConceptUri() {
    return this.ontologyConceptUri;
  }

  public void setOntologyConceptUri(String ontologyConceptUri) {
    this.ontologyConceptUri = ontologyConceptUri;
  }

  public String getIndicatorName() {
    return this.indicatorName;
  }

  public void setIndicatorName(String indicatorName) {
    this.indicatorName = indicatorName;
  }

  public Set getSentimentIndicators() {
    return this.sentimentIndicators;
  }

  public void setSentimentIndicators(Set sentimentIndicators) {
    this.sentimentIndicators = sentimentIndicators;
  }

}
