package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PhraseType generated by hbm2java
 */
public class PhraseType implements java.io.Serializable {

  private long id;
  private String name;
  private String description;
  private Set phrases = new HashSet(0);

  public PhraseType() {
  }

  public PhraseType(long id) {
    this.id = id;
  }

  public PhraseType(long id, String name, String description, Set phrases) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.phrases = phrases;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Set getPhrases() {
    return this.phrases;
  }

  public void setPhrases(Set phrases) {
    this.phrases = phrases;
  }

}
