package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

/**
 * SentimentPhraseRelation generated by hbm2java
 */
public class SentimentPhraseRelation implements java.io.Serializable {

  private long id;
  private Sentiment sentiment;
  private Phrase phrase;

  public SentimentPhraseRelation() {
  }

  public SentimentPhraseRelation(long id, Sentiment sentiment, Phrase phrase) {
    this.id = id;
    this.sentiment = sentiment;
    this.phrase = phrase;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Sentiment getSentiment() {
    return this.sentiment;
  }

  public void setSentiment(Sentiment sentiment) {
    this.sentiment = sentiment;
  }

  public Phrase getPhrase() {
    return this.phrase;
  }

  public void setPhrase(Phrase phrase) {
    this.phrase = phrase;
  }

}
