package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SentimentObjectType generated by hbm2java
 */
public class SentimentObjectType implements java.io.Serializable {

  private long id;
  private String name;
  private String ontologyConceptUri;
  private Set sentimentObjects = new HashSet(0);

  public SentimentObjectType() {
  }

  public SentimentObjectType(long id, String name) {
    this.id = id;
    this.name = name;
  }

  public SentimentObjectType(long id, String name, String ontologyConceptUri, Set sentimentObjects) {
    this.id = id;
    this.name = name;
    this.ontologyConceptUri = ontologyConceptUri;
    this.sentimentObjects = sentimentObjects;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getOntologyConceptUri() {
    return this.ontologyConceptUri;
  }

  public void setOntologyConceptUri(String ontologyConceptUri) {
    this.ontologyConceptUri = ontologyConceptUri;
  }

  public Set getSentimentObjects() {
    return this.sentimentObjects;
  }

  public void setSentimentObjects(Set sentimentObjects) {
    this.sentimentObjects = sentimentObjects;
  }

}
