package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SentimentFeatureType generated by hbm2java
 */
public class SentimentFeatureType implements java.io.Serializable {

  private long id;
  private String name;
  private String ontologyConceptUri;
  private Set sentimentsForSentimentFeatureTypeFk = new HashSet(0);
  private Set sentimentsForSentimentSubfeatureTypeFk = new HashSet(0);

  public SentimentFeatureType() {
  }

  public SentimentFeatureType(long id, String name) {
    this.id = id;
    this.name = name;
  }

  public SentimentFeatureType(long id, String name, String ontologyConceptUri,
                              Set sentimentsForSentimentFeatureTypeFk,
                              Set sentimentsForSentimentSubfeatureTypeFk) {
    this.id = id;
    this.name = name;
    this.ontologyConceptUri = ontologyConceptUri;
    this.sentimentsForSentimentFeatureTypeFk = sentimentsForSentimentFeatureTypeFk;
    this.sentimentsForSentimentSubfeatureTypeFk = sentimentsForSentimentSubfeatureTypeFk;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getOntologyConceptUri() {
    return this.ontologyConceptUri;
  }

  public void setOntologyConceptUri(String ontologyConceptUri) {
    this.ontologyConceptUri = ontologyConceptUri;
  }

  public Set getSentimentsForSentimentFeatureTypeFk() {
    return this.sentimentsForSentimentFeatureTypeFk;
  }

  public void setSentimentsForSentimentFeatureTypeFk(Set sentimentsForSentimentFeatureTypeFk) {
    this.sentimentsForSentimentFeatureTypeFk = sentimentsForSentimentFeatureTypeFk;
  }

  public Set getSentimentsForSentimentSubfeatureTypeFk() {
    return this.sentimentsForSentimentSubfeatureTypeFk;
  }

  public void setSentimentsForSentimentSubfeatureTypeFk(Set sentimentsForSentimentSubfeatureTypeFk) {
    this.sentimentsForSentimentSubfeatureTypeFk = sentimentsForSentimentSubfeatureTypeFk;
  }

}
