package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

/**
 * SentimentObjectProperty generated by hbm2java
 */
public class SentimentObjectProperty implements java.io.Serializable {

  private long id;
  private String value;
  private String key;

  public SentimentObjectProperty() {
  }

  public SentimentObjectProperty(long id) {
    this.id = id;
  }

  public SentimentObjectProperty(long id, String value, String key) {
    this.id = id;
    this.value = value;
    this.key = key;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public String getKey() {
    return this.key;
  }

  public void setKey(String key) {
    this.key = key;
  }

}
