package hibernate.entities;

// Generated Jul 5, 2012 11:27:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SentimentObject generated by hbm2java
 */
public class SentimentObject implements java.io.Serializable {

  private long id;
  private SentimentObjectType sentimentObjectType;
  private String ontologyConceptUri;
  private String name;
  private Set sentiments = new HashSet(0);

  public SentimentObject() {
  }

  public SentimentObject(long id) {
    this.id = id;
  }

  public SentimentObject(long id, SentimentObjectType sentimentObjectType, String ontologyConceptUri,
                         String name, Set sentiments) {
    this.id = id;
    this.sentimentObjectType = sentimentObjectType;
    this.ontologyConceptUri = ontologyConceptUri;
    this.name = name;
    this.sentiments = sentiments;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public SentimentObjectType getSentimentObjectType() {
    return this.sentimentObjectType;
  }

  public void setSentimentObjectType(SentimentObjectType sentimentObjectType) {
    this.sentimentObjectType = sentimentObjectType;
  }

  public String getOntologyConceptUri() {
    return this.ontologyConceptUri;
  }

  public void setOntologyConceptUri(String ontologyConceptUri) {
    this.ontologyConceptUri = ontologyConceptUri;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getSentiments() {
    return this.sentiments;
  }

  public void setSentiments(Set sentiments) {
    this.sentiments = sentiments;
  }

}
