package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SentimentIndicator generated by hbm2java
 */
public class SentimentIndicator implements java.io.Serializable {

  private long id;
  private IndicatorType indicatorType;
  private Indicator indicator;
  private String name;
  private Long indicatorScore;
  private Long positiveDomNumber;
  private Long negativeDomNumber;
  private Integer correlationDefinition;
  private Set sentiments = new HashSet(0);

  public SentimentIndicator() {
  }

  public SentimentIndicator(long id) {
    this.id = id;
  }

  public SentimentIndicator(long id, IndicatorType indicatorType, Indicator indicator, String name,
                            Long indicatorScore, Long positiveDomNumber, Long negativeDomNumber,
                            Integer correlationDefinition, Set sentiments) {
    this.id = id;
    this.indicatorType = indicatorType;
    this.indicator = indicator;
    this.name = name;
    this.indicatorScore = indicatorScore;
    this.positiveDomNumber = positiveDomNumber;
    this.negativeDomNumber = negativeDomNumber;
    this.correlationDefinition = correlationDefinition;
    this.sentiments = sentiments;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public IndicatorType getIndicatorType() {
    return this.indicatorType;
  }

  public void setIndicatorType(IndicatorType indicatorType) {
    this.indicatorType = indicatorType;
  }

  public Indicator getIndicator() {
    return this.indicator;
  }

  public void setIndicator(Indicator indicator) {
    this.indicator = indicator;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getIndicatorScore() {
    return this.indicatorScore;
  }

  public void setIndicatorScore(Long indicatorScore) {
    this.indicatorScore = indicatorScore;
  }

  public Long getPositiveDomNumber() {
    return this.positiveDomNumber;
  }

  public void setPositiveDomNumber(Long positiveDomNumber) {
    this.positiveDomNumber = positiveDomNumber;
  }

  public Long getNegativeDomNumber() {
    return this.negativeDomNumber;
  }

  public void setNegativeDomNumber(Long negativeDomNumber) {
    this.negativeDomNumber = negativeDomNumber;
  }

  public Integer getCorrelationDefinition() {
    return this.correlationDefinition;
  }

  public void setCorrelationDefinition(Integer correlationDefinition) {
    this.correlationDefinition = correlationDefinition;
  }

  public Set getSentiments() {
    return this.sentiments;
  }

  public void setSentiments(Set sentiments) {
    this.sentiments = sentiments;
  }

}
