package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SentimentClassifierType generated by hbm2java
 */
public class SentimentClassifierType implements java.io.Serializable {

  private long id;
  private String classifierMethod;
  private String sentimentType;
  private Set sentiments = new HashSet(0);

  public SentimentClassifierType() {
  }

  public SentimentClassifierType(long id) {
    this.id = id;
  }

  public SentimentClassifierType(long id, String classifierMethod, String sentimentType, Set sentiments) {
    this.id = id;
    this.classifierMethod = classifierMethod;
    this.sentimentType = sentimentType;
    this.sentiments = sentiments;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getClassifierMethod() {
    return this.classifierMethod;
  }

  public void setClassifierMethod(String classifierMethod) {
    this.classifierMethod = classifierMethod;
  }

  public String getSentimentType() {
    return this.sentimentType;
  }

  public void setSentimentType(String sentimentType) {
    this.sentimentType = sentimentType;
  }

  public Set getSentiments() {
    return this.sentiments;
  }

  public void setSentiments(Set sentiments) {
    this.sentiments = sentiments;
  }

}
