package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sentiment generated by hbm2java
 */
public class Sentiment implements java.io.Serializable {

  private long id;
  private SentimentFeatureType sentimentSubFeatureType;
  private DegreeOfMembership negativeDOMs;
  private DocumentMetaData documentMetaData;
  private DegreeOfMembership holderCertaintyDOMs;
  private DegreeOfMembership positiveDOMs;
  private SentimentLevelDefinition sentimentLevelDefinition;
  private SentimentObject sentimentObject;
  private SentimentClassifierType sentimentClassifierType;
  private SentimentIndicator indicator;
  private SentimentFeatureType sentimentFeatureType;
  private BigDecimal score;
  private Integer paragraph;
  private Set sentimentPhraseRelations = new HashSet(0);

  public Sentiment() {
  }

  public Sentiment(long id) {
    this.id = id;
  }

  public Sentiment(long id, SentimentFeatureType sentimentSubFeatureType,
                   DegreeOfMembership negativeDOMs, DocumentMetaData documentMetaData,
                   DegreeOfMembership holderCertaintyDOMs, DegreeOfMembership positiveDOMs,
                   SentimentLevelDefinition sentimentLevelDefinition, SentimentObject sentimentObject,
                   SentimentClassifierType sentimentClassifierType, SentimentIndicator indicator,
                   SentimentFeatureType sentimentFeatureType, BigDecimal score, Integer paragraph,
                   Set sentimentPhraseRelations) {
    this.id = id;
    this.sentimentSubFeatureType = sentimentSubFeatureType;
    this.negativeDOMs = negativeDOMs;
    this.documentMetaData = documentMetaData;
    this.holderCertaintyDOMs = holderCertaintyDOMs;
    this.positiveDOMs = positiveDOMs;
    this.sentimentLevelDefinition = sentimentLevelDefinition;
    this.sentimentObject = sentimentObject;
    this.sentimentClassifierType = sentimentClassifierType;
    this.indicator = indicator;
    this.sentimentFeatureType = sentimentFeatureType;
    this.score = score;
    this.paragraph = paragraph;
    this.sentimentPhraseRelations = sentimentPhraseRelations;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public SentimentFeatureType getSentimentSubFeatureType() {
    return this.sentimentSubFeatureType;
  }

  public void setSentimentSubFeatureType(SentimentFeatureType sentimentSubFeatureType) {
    this.sentimentSubFeatureType = sentimentSubFeatureType;
  }

  public DegreeOfMembership getNegativeDOMs() {
    return this.negativeDOMs;
  }

  public void setNegativeDOMs(DegreeOfMembership negativeDOMs) {
    this.negativeDOMs = negativeDOMs;
  }

  public DocumentMetaData getDocumentMetaData() {
    return this.documentMetaData;
  }

  public void setDocumentMetaData(DocumentMetaData documentMetaData) {
    this.documentMetaData = documentMetaData;
  }

  public DegreeOfMembership getHolderCertaintyDOMs() {
    return this.holderCertaintyDOMs;
  }

  public void setHolderCertaintyDOMs(DegreeOfMembership holderCertaintyDOMs) {
    this.holderCertaintyDOMs = holderCertaintyDOMs;
  }

  public DegreeOfMembership getPositiveDOMs() {
    return this.positiveDOMs;
  }

  public void setPositiveDOMs(DegreeOfMembership positiveDOMs) {
    this.positiveDOMs = positiveDOMs;
  }

  public SentimentLevelDefinition getSentimentLevelDefinition() {
    return this.sentimentLevelDefinition;
  }

  public void setSentimentLevelDefinition(SentimentLevelDefinition sentimentLevelDefinition) {
    this.sentimentLevelDefinition = sentimentLevelDefinition;
  }

  public SentimentObject getSentimentObject() {
    return this.sentimentObject;
  }

  public void setSentimentObject(SentimentObject sentimentObject) {
    this.sentimentObject = sentimentObject;
  }

  public SentimentClassifierType getSentimentClassifierType() {
    return this.sentimentClassifierType;
  }

  public void setSentimentClassifierType(SentimentClassifierType sentimentClassifierType) {
    this.sentimentClassifierType = sentimentClassifierType;
  }

  public SentimentIndicator getIndicator() {
    return this.indicator;
  }

  public void setIndicator(SentimentIndicator indicator) {
    this.indicator = indicator;
  }

  public SentimentFeatureType getSentimentFeatureType() {
    return this.sentimentFeatureType;
  }

  public void setSentimentFeatureType(SentimentFeatureType sentimentFeatureType) {
    this.sentimentFeatureType = sentimentFeatureType;
  }

  public BigDecimal getScore() {
    return this.score;
  }

  public void setScore(BigDecimal score) {
    this.score = score;
  }

  public Integer getParagraph() {
    return this.paragraph;
  }

  public void setParagraph(Integer paragraph) {
    this.paragraph = paragraph;
  }

  public Set getSentimentPhraseRelations() {
    return this.sentimentPhraseRelations;
  }

  public void setSentimentPhraseRelations(Set sentimentPhraseRelations) {
    this.sentimentPhraseRelations = sentimentPhraseRelations;
  }

}
