package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SentimentLevelDefinition generated by hbm2java
 */
public class SentimentLevelDefinition implements java.io.Serializable {

  private long id;
  private String name;
  private Set sentiments = new HashSet(0);

  public SentimentLevelDefinition() {
  }
  
  public SentimentLevelDefinition(long id, String name) {
    this.id = id;
    this.name = name;
  }

  public SentimentLevelDefinition(long id, String name, Set sentiments) {
    this.id = id;
    this.name = name;
    this.sentiments = sentiments;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getSentiments() {
    return this.sentiments;
  }

  public void setSentiments(Set sentiments) {
    this.sentiments = sentiments;
  }

}
