package hibernate.entities;

// Generated Aug 13, 2012 4:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Website generated by hbm2java
 */
public class Website implements java.io.Serializable {

  private long id;
  private String title;
  private String author;
  private String url;
  private Set documentMetaDatas = new HashSet(0);

  public Website() {
  }

  public Website(long id) {
    this.id = id;
  }

  public Website(long id, String title, String author, String url, Set documentMetaDatas) {
    this.id = id;
    this.title = title;
    this.author = author;
    this.url = url;
    this.documentMetaDatas = documentMetaDatas;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getAuthor() {
    return this.author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Set getDocumentMetaDatas() {
    return this.documentMetaDatas;
  }

  public void setDocumentMetaDatas(Set documentMetaDatas) {
    this.documentMetaDatas = documentMetaDatas;
  }

}
